### ISSUE TITLE
Camera Pose Coordinate Convention

### ISSUE THREAD

**Issue by colin-de** [princeton-computational-imaging/HNDR#3]
Hi! Thanks for the great work. I wonder what's the camera coordination convention(i.e. OpenCV / Colmap) used in this project?
```Camera Info at Frame 0: 
World to Camera Transform: 
 [[ 0.13201442  0.02732324  0.99087113 -0.03884006]
 [ 0.401116    0.9126483  -0.07860719 -0.16735849]
 [-0.90646446  0.40783158  0.1095229   0.24308646]
 [ 0.          0.          0.          1.0000001 ]] 
```

**Comment by Ilya-Muromets** [comment]
The convention is "Apple convention" as I'm collecting ARKit transform values, see:

https://developer.apple.com/documentation/avfoundation/avcameracalibrationdata/2881130-extrinsicmatrix
and
https://developer.apple.com/documentation/arkit/arcamera/2866108-transform
