### ISSUE TITLE
Can I use the front-facing depth camera

### ISSUE THREAD

**Issue by wahiahia** [princeton-computational-imaging/HNDR#4]

**Comment by Ilya-Muromets** [comment]
In theory, yes, but you'll have to play around with some coordinate conventions and with the data capture app (see: [capturedDepthData](https://developer.apple.com/documentation/arkit/arframe/2928208-captureddepthdata) and [ARFaceTrackingConfiguration](https://developer.apple.com/documentation/arkit/arfacetrackingconfiguration) ).

Also keep in mind that if you are trying to reconstruct objects like someone's actual face, you now have to model both the motion of your camera and of the object, as people are not perfectly static.

Best of luck,
Ilya
